name: CICD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build-image
        run: |
          IMAGE_TAG=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g')
          IMAGE_NAME=abinoveramesh/$IMAGE_TAG:latest
          docker build -t $IMAGE_NAME .
          echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ steps.build-image.outputs.image_name }}

      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            cd /var/www/html/project
            git pull origin branch
            composer install
